import pygame
HIGHLIGHT_COLOR = (255, 255, 0)  # Yellow
WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 700
GRAY = (200, 200, 200)
BLACK = (0,0,0)
CARD_WIDTH = 100
CARD_HEIGHT = 150
CARD_MARGIN = 10
FONT_PATH = pygame.font.match_font("arial")
MOVEMENT_KEYS = ( pygame.K_UP,pygame.K_DOWN,pygame.K_RIGHT,pygame.K_LEFT )
SELECTION_KEYS = (pygame.K_SPACE,pygame.K_RETURN)
SELECT_MODE = pygame.USEREVENT + 1
DEBUG = True

NUM_PLAYERS = 2